---
##################################
# Edit this section:
PATH_hg38: "/path/to/hg38.fa"
PATH_hg38_dict: "/path/to/hg38.dict"
PATH_bed: "/path/to/panel_targets.bed"
PATH_bed_intervals: "/path/to/panel_targets.interval_list"
PATH_baits: "/path/to/panel_baits.interval_list"
PATH_germline: "/path/to/Mutect/germline_resources/af-only-gnomad.hg38.vcf.gz"
PATH_PoN: "/path/to/Mutect/pon.vcf.gz"
PATH_known_indels: "/path/to/dbSNP/resources_broad_hg38_v0_Homo_sapiens_assembly38.known_indels.vcf"
PATH_gold_std_indels: "/path/to/dbSNP/resources_broad_hg38_v0_Mills_and_1000G_gold_standard.indels.hg38.vcf"
PATH_SNP_db: "/path/to/dbSNP/resources_broad_hg38_v0_Homo_sapiens_assembly38.dbsnp138.vcf"
PATH_ANNOVAR: "/path/to/annovar"
TMPDIR: "path/to/tmpdir"
##################################

PATH_adapters: "resources/references/adapters.fa"
DIR_sample_maps: "resources/sample_maps"

# data files
DIR_results: "results"
DIR_fastq: "results/data/fastq"
DIR_bams: "results/data/bam"
DIR_metrics: "results/metrics"

# figures 
DIR_insertsize_figures: "results/figures/insert_size"
DIR_insertsize_figures_PNG: "results/figures/insert_size_PNG"