---
# PATH_hg38: "/groups/wyattgrp/users/jbacon/reference/CHIP_hg38_fix/GRCh38.u2af1_fix.v1.2020_04_01.filtered.fa"
PATH_hg38: "/groups/wyattgrp/users/jbacon/reference/matti_hg38/hg38_masked.fa"
PATH_hg38_dict: "/groups/wyattgrp/users/jbacon/reference/CHIP_hg38_fix/GRCh38.u2af1_fix.v1.2020_04_01.filtered.dict"
PATH_bed: "/groups/wyattgrp/users/amunzur/pipeline/resources/panel/CHIP/CHIP_targets.bed"
PATH_bed_intervals: "/groups/wyattgrp/users/amunzur/pipeline/resources/panel/CHIP/CHIP_targets.interval_list"
PATH_baits: "/groups/wyattgrp/users/amunzur/pipeline/resources/panel/CHIP/CHIP_baits.anno.interval_list"
PATH_germline: "/groups/wyattgrp/users/amunzur/pipeline/resources/Mutect/germline_resources/af-only-gnomad.hg38.vcf.gz"
PATH_PoN: "/groups/wyattgrp/users/amunzur/pipeline/resources/Mutect/pon.vcf.gz"
PATH_adapters: "resources/references/adapters.fa"
DIR_sample_maps: "resources/sample_maps"
PATH_known_indels: "/groups/wyattgrp/users/jbacon/reference/dbSNP/resources_broad_hg38_v0_Homo_sapiens_assembly38.known_indels.vcf"
PATH_gold_std_indels: "/groups/wyattgrp/users/jbacon/reference/dbSNP/resources_broad_hg38_v0_Mills_and_1000G_gold_standard.indels.hg38.vcf"
PATH_SNP_db: "/groups/wyattgrp/users/jbacon/reference/dbSNP/resources_broad_hg38_v0_Homo_sapiens_assembly38.dbsnp138.vcf"

# data files
DIR_results: "results"
DIR_fastq: "results/data/fastq"
DIR_bams: "results/data/bam"
DIR_metrics: "results/metrics"

# cnvkit
cnvkit_targets_bed: "resources/cnvkit/my_targets.bed"
cfDNA_reference: "results/cnvkit/references/VIP_cfDNA_reference.cnn"
WBC_reference: "results/cnvkit/references/VIP_WBC_reference.cnn"
chip_probes_bed: "/groups/wyattgrp/users/jbacon/reference/bed_files/CHIP/CHIP_probes.bed"

# figures 
DIR_insertsize_figures: "results/figures/insert_size"
DIR_insertsize_figures_PNG: "results/figures/insert_size_PNG"